Pgebheim/experimental connector
AugurProject/augur pull request #2202
Opened 2019-05-18 16:12 UTC by pgebheim

2019-05-18 16:16 UTC, pgebheim commented
@justinbarry -- Here is my first draft of this.

- It uses cross-fetch to bring in a cross-env `fetch` polyfill.
- It only supports HTTP at the moment
- The test is written inline 'cause I didn't spend the time to figure out how/where you're putting the tests for this stuff, this comes with a npm script called `connect` for @augurproject/sdk which just runs that one test. That should be refactored.

General thoughts:
- Augur SDK needs a pass to get the styles the same. We have multiple file name formats for classes etc.
- There are places where we are explicitly importing from `src` -- this will break as soon as this is used as an NPM module. Can't TS automatically point the module at `src` in TS-land so that when its an npm module the main `build` directory will be isomorphic to the old `src` dir and relative imports would still work?

2019-05-20 16:29 UTC, justinbarry commented
1. Added discriminant union code to #2183.
2. Added code style issue #2207.

2019-05-20 16:59 UTC, justinbarry commented on packages/augur-sdk/src/connector/http-connector.ts
> +// TODO: use cross-fetch?
```suggestion

```

Yes. Unless you prefer another package.

2019-05-20 16:59 UTC, justinbarry commented on packages/augur-sdk/src/connector/http-connector.ts
> +
```suggestion
return Promise.resolve();
```

2019-05-20 17:00 UTC, justinbarry commented on packages/augur-sdk/src/connector/http-connector.ts
> +
```suggestion
return Promise.resolve();
```

2019-05-20 17:04 UTC, justinbarry requested changes
Requested simple changes. Otherwise looks good!

2019-05-20 17:18 UTC, pgebheim commented
@brianosaurus -- Here is my solution to the `sender` thing.

2019-05-20 17:41 UTC, brianosaurus commented
@justinbarry, if main in pakage.json points to src or build it'll automatically find the include. You and I chatted about a while ago. 

LGTM, I'll absorb this into the mostly finished websocket stuff. Personally I would have implemented BindTo in the base class and then just did comm out of the individual connectors. Pass it back and let API deal with deserializing  CC: @pgebheim

2019-05-20 18:34 UTC, justinbarry approved these changes

2019-05-20 20:36 UTC, merged