Implement getDisputeWindow getter & tests
AugurProject/augur pull request #3361
Opened 2019-08-26 23:59 UTC by robert-e-davidson3

2019-08-27 00:10 UTC, bthaile commented
This getter isnt for the user. The amount of participation tokens purchased is total not by user. User specific data will go on getUserReporting history getter.

2019-08-27 00:14 UTC, bthaile commented on packages/augur-sdk/src/state/getter/Universe.ts
> +    const account = await augur.getAccount();
this isn't account specific getter

2019-08-27 00:14 UTC, bthaile commented on packages/augur-sdk/src/state/getter/Universe.ts
> +    if (currentDisputeWindow === null) return null;
dispute window should never be null. it will need to be created.

2019-08-27 00:16 UTC, bthaile commented on packages/augur-test/src/tests/state/getter/Universe.test.ts
> +  test('getDisputeWindow', async () => {
I'm thinking, need to test for sdk to create a dispute window by calling method on universe and verifying a dispute window is created.

2019-08-27 00:31 UTC, robert-e-davidson3 commented on packages/augur-test/src/tests/state/getter/Universe.test.ts
> +  test('getDisputeWindow', async () => {
That solution bothers me. Aside from the naming issue (getters shouldn't set), how will that look to the user? They navigate to the dispute page and get a metamask popup? That might be the right flow but I think I'd be more comfortable with a version of the dispute window page that has a clearly-labelled button for creating the dispute window.

2019-08-28 07:03 UTC, ghost reviewed
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 👌

 This link will always point to this PR's latest changes: https://peek.run/1rehxn2

2019-08-28 17:55 UTC, robert-e-davidson3 commented on packages/augur-sdk/src/state/getter/Universe.ts
> +      endTime: `0x${currentTime.toString(16)}`,
@bthaile I'm worried about this part. I couldn't think of a good default to use so I went with something obviously wrong. My thinking is that users will find it less confusing if they see an obviously wrong date range suddenly change into the correct date change (when the dispute window is created) than if a valid-looking dispute window suddenly changes its range.

2019-08-28 18:25 UTC, bthaile commented on packages/augur-sdk/src/state/getter/Universe.ts
> +      endTime: `0x${currentTime.toString(16)}`,
just make end time 0

2019-08-28 18:27 UTC, bthaile commented on packages/augur-sdk/src/state/getter/Universe.ts
> +  endTime: Timestamp;
lets be consistent with timestamps. 
Users.ts uses number `  endTime: t.number,` 
we don't need BigNumber or string for timestamps, imo

2019-08-28 18:29 UTC, bthaile requested changes
lgtm, few changes

2019-08-28 21:13 UTC, robert-e-davidson3 commented on packages/augur-sdk/src/state/getter/Universe.ts
> +  endTime: Timestamp;
done!

2019-08-28 21:21 UTC, bthaile commented on packages/augur-sdk/src/state/getter/Universe.ts
> +      purchased: purchased.toNumber(),
This needs to be a string. could be very large

2019-08-28 21:21 UTC, bthaile commented on packages/augur-sdk/src/state/getter/Universe.ts
> +      fees: fees.toNumber(),
same here, could be very large

2019-08-28 21:59 UTC, bthaile approved these changes
lgtm, nice!!! 👍

2019-08-29 04:48 UTC, merged