Sort dispute outcome order
AugurProject/augur pull request #3664
Opened 2019-09-16 20:59 UTC by bthaile

only Yes No and categorical markets sort correctly

https://github.com/augurproject/augur/issues/3628

I'll get another PR in for scalar markets. 

![image](https://user-images.githubusercontent.com/3970376/64992972-a10c1e80-d89a-11e9-9996-3dd603db27ae.png)

2019-09-16 21:18 UTC, phoebemirman requested changes
<img width="879" alt="Screen Shot 2019-09-16 at 2 18 09 PM" src="https://user-images.githubusercontent.com/6775839/64994184-d578de00-d88c-11e9-8346-deb69d07bdd4.png">
<img width="819" alt="Screen Shot 2019-09-16 at 2 17 54 PM" src="https://user-images.githubusercontent.com/6775839/64994185-d578de00-d88c-11e9-8a93-5a6adf2d10de.png">
shouldn't tentative winner be showing up first?

2019-09-16 22:24 UTC, ghost reviewed
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 🆒

 This link will always point to this PR's latest changes: https://peek.run/93ph301

2019-09-16 23:12 UTC, JohnDanz approved these changes
just remove those console logs and looks good

2019-09-16 23:12 UTC, JohnDanz commented on packages/augur-ui/src/modules/markets/selectors/market.ts
> +    console.log("yes no, cat")
remove this log

2019-09-16 23:12 UTC, JohnDanz commented on packages/augur-ui/src/modules/markets/selectors/market.ts
> +    stakes.map(s => console.log(JSON.stringify(s)));
and this one

2019-09-17 13:44 UTC, bthaile commented
need alex's PR merged to use the new properties on DisputeInfo. closing

2019-09-17 23:47 UTC, phoebemirman approved these changes

2019-09-18 12:27 UTC, merged