proptype conversions
AugurProject/augur pull request #3785
Opened 2019-09-24 04:49 UTC by mjgiannelli

https://github.com/AugurProject/augur/issues/3393b

2019-09-24 04:56 UTC, bthaile commented on packages/augur-ui/src/modules/create-market/components/create-market-view/create-market-view.tsx
> +  history: Object;
Move the HistoryObject interface to types.ts and reference it here and not Object.

2019-09-24 04:57 UTC, bthaile commented on packages/augur-ui/src/modules/create-market/components/create-market-view/create-market-view.tsx
> +  newMarket: Object;
We have a ‘NewMarket’ type in types.ts. Reference it here instead of Object.

2019-09-24 04:58 UTC, bthaile commented on packages/augur-ui/src/modules/create-market/components/create-market-view/create-market-view.tsx
> +  universe: Object;
I think we have Universe interface in types.ts. Reference here instead of Object

2019-09-24 04:59 UTC, bthaile commented on packages/augur-ui/src/modules/create-market/components/create-market-view/create-market-view.tsx
> +  meta: Object;
Leave meta as Object, I’m bot sure about it.

2019-09-24 05:01 UTC, bthaile commented on packages/augur-ui/src/modules/market/components/common/module-tabs/module-pane.tsx
> +  children: any;
children I think is React.ReactNode or Element. Leave it as any.

2019-09-24 05:02 UTC, bthaile commented on packages/augur-ui/src/modules/market/components/core-properties/core-properties.tsx
> +  market: Object;
market is “MarketData” not Object. Interface is in types.ts

2019-09-24 05:03 UTC, bthaile commented on packages/augur-ui/src/modules/market/components/market-header/market-header-collapsed.tsx
> +  market: object;
market is “MarketData”, interface is int types.ta

2019-09-24 05:04 UTC, bthaile commented on packages/augur-ui/src/modules/market/components/market-header/market-header-reporting.tsx
> +  market: Object;
market is “MarketData”, interface is int types.ts

2019-09-24 05:06 UTC, bthaile commented on packages/augur-ui/src/modules/market/components/market-header/market-header-reporting.tsx
> +  tentativeWinner?: Object;
TentativeWinner can be left as Object. Its going to be refactored.

2019-09-24 05:07 UTC, bthaile requested changes
Few nit pics.

2019-09-26 01:10 UTC, pgebheim commented
@mjgiannelli -- closing this PR. Please address feedback and make another.

2019-09-26 01:10 UTC, closed without merging