Update dispute notification
AugurProject/augur pull request #3804
Opened 2019-09-24 20:15 UTC by adrake33

Closes #3781

2019-09-24 20:27 UTC, ghost reviewed
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 🌈

 This link will always point to this PR's latest changes: https://peek.run/4kgh577

2019-09-25 01:22 UTC, bthaile commented on packages/augur-ui/src/modules/notifications/selectors/notification-state.ts
> +      .loginAccount.reporting.disputing.contracts.map(obj => obj.marketId);
either one of these can be null. 
state.loginAccount.reporting.reporting
state.loginAccount.reporting.disputing

also, I don't see markets where user has created.

2019-09-25 01:23 UTC, bthaile requested changes
need null checks and get markets where user created markets for dispute notification

2019-09-25 02:16 UTC, adrake33 commented
> need null checks and get markets where user created markets for dispute notification

Yeah, good point. I added checks to see if those are null. The check for whether the user is the creator is in the filter below: ```(market.reportingState ===
              MarketReportingState.CrowdsourcingDispute &&
              (market.author === address ||
                positionsMarkets.indexOf(market.id) > -1)```

2019-09-25 22:21 UTC, bthaile approved these changes
lgtm

2019-09-25 22:37 UTC, merged