was adding total for market instead of amount of reporting or disputing
AugurProject/augur pull request #3860
Opened 2019-09-26 22:41 UTC by bthaile

fix bug when summing up reporting / disputing staked REP

2019-09-26 22:50 UTC, bconfortin requested changes

2019-09-26 22:50 UTC, bconfortin commented on packages/augur-ui/src/modules/positions/selectors/select-reporting-winnings-by-market.ts
>    return (
This will break if market is null or undefined.

I guess you meant only to remove the `console.log()` but removed the whole `if` statement

2019-09-26 23:02 UTC, ghost reviewed
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 📈

 This link will always point to this PR's latest changes: https://peek.run/2n5hlnm

2019-09-27 02:13 UTC, bthaile commented
changes made, comment addressed

2019-09-27 03:05 UTC, bthaile commented
closing combining PRs

2019-09-27 03:05 UTC, closed without merging

2019-09-27 12:41 UTC, bconfortin commented on packages/augur-ui/src/modules/positions/selectors/select-reporting-winnings-by-market.ts
> +  if (createBigNumber(amount).lte(ZERO)) return false;
Nice performance boost here.