0x v3 adjustments and API fixes
AugurProject/augur pull request #4289
Opened 2019-10-18 07:40 UTC by nuevoalex

v3 0x requires a protocol fee be paid by takers in ETH, so we support that now.

Also modified the browser mesh API interface to match what it will actually be and adjust logic in the API to prioritize usage of browser mesh or client api.

2019-10-18 19:21 UTC, justinbarry approved these changes
LGTM

2019-10-28 22:27 UTC, robert-e-davidson3 commented
`contracts.json` is empty now but needs to exist

2019-10-28 22:27 UTC, robert-e-davidson3 requested changes
`contracts.json` is empty but needs content

2019-10-28 22:40 UTC, robert-e-davidson3 approved these changes

2019-10-30 02:35 UTC, merged