Unsafe: refactor UNSAFE_ methods from /common/
AugurProject/augur pull request #4539
Opened 2019-10-31 22:47 UTC by gitstart-augur

#4341  
- Fixed initial reverted PR.

2019-10-31 23:01 UTC, ghost reviewed
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 🥇
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/5m3h33q**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

2019-11-01 02:58 UTC, bthaile commented
![image](https://user-images.githubusercontent.com/3970376/67999247-7b0fc300-fc29-11e9-95d7-d957da409bbc.png)

2019-11-01 02:58 UTC, bthaile commented on packages/augur-ui/src/modules/common/form.tsx
>        nextProps.canToggleVisibility &&
nextProps is no longer defined. Just bring up the Ui would have found this in about 1 second

2019-11-01 02:59 UTC, bthaile requested changes
need to test before submitting PR

2019-11-05 18:33 UTC, pgebheim commented
@gitstart-augur -- Did that force push address @bthaile's issue?

2019-11-11 23:33 UTC, pgebheim commented
Is this being fixed in #4695, #4964, #4696 ?

2019-11-12 13:11 UTC, gitstart-augur commented
Yes @pgebheim  this has been fixed.

2019-11-12 17:28 UTC, pgebheim commented
@bthaile mind doing a review?

2019-11-12 20:08 UTC, bthaile commented
@bconfortin can you review this PR. Make sure to pull it down and click around

2019-11-12 23:40 UTC, bconfortin requested changes
TextInput is breaking and Input is not working as intended.
After you fix those two, I suggest taking 5-10 minutes testing and checking if you don't have any console errors.

The other components seems to be working properly. Good job.

2019-11-12 23:53 UTC, bthaile commented
I'm thinking too much context is needed to work these refactor tasks.

2019-11-14 07:19 UTC, gitstart-augur commented
@bthaile  @bconfortin  We fixed breaking TextInput. Also took some time to go through the whole site while having my console open(Should do that going forward). 
For Upcoming PR's i will be asking questions in the channel for test context i miss in case of any.

2019-11-14 17:42 UTC, bconfortin commented
TextInput and Input seems to be working now. Nice job.

2019-11-14 18:58 UTC, bconfortin approved these changes

2019-11-19 01:38 UTC, bthaile approved these changes
Lgtm

2019-11-19 01:38 UTC, merged