Non weekend date year
AugurProject/augur pull request #5338
Opened 2019-12-29 23:17 UTC by bthaile

dont allow user to create template finance market where date picked is on a weekend.

2019-12-29 23:29 UTC, ghost reviewed
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 🆒
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/654hjjz**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

2019-12-30 18:30 UTC, phoebemirman commented on packages/augur-ui/src/modules/common/validations.ts
> +            return 'weekday is required';
can this be capitalized?

2019-12-30 18:30 UTC, bthaile commented on packages/augur-ui/src/modules/common/validations.ts
> +            return 'weekday is required';
sure

2019-12-30 18:38 UTC, phoebemirman requested changes
<img width="791" alt="Screen Shot 2019-12-30 at 10 36 33 AM" src="https://user-images.githubusercontent.com/6775839/71595437-829bfd00-2af0-11ea-8548-b53d080a6fc7.png">

seems the event expiration should happen after the start date error isn't showing up here

2019-12-30 21:46 UTC, phoebemirman approved these changes

2019-12-30 23:51 UTC, merged