Inverting Help Icon color to match spec.
AugurProject/augur pull request #5478
Opened 2020-01-10 17:08 UTC by jfarid27

## Description

Updates the Help Icon to an inverted color to match spec.

## Screenshots

### Destop
![Screenshot from 2020-01-10 12-04-29](https://user-images.githubusercontent.com/1673206/72171655-6b3afa80-33a1-11ea-99a9-389de5f9386d.png)

### Mobile
![Screenshot from 2020-01-10 12-04-38](https://user-images.githubusercontent.com/1673206/72171658-6d04be00-33a1-11ea-9953-313668cb4ef3.png)

## Issues

#5207
#5206
#5202
#5201

2020-01-12 15:12 UTC, bthaile commented
colors for the UI are located here. We try to not use in-line colors. We are going to have theming down the road.
augur/packages/augur-ui/src/assets/styles/_colors.less

2020-01-12 15:12 UTC, bthaile requested changes
see comment

2020-01-12 23:40 UTC, jfarid27 reviewed
@bthaile Got it. It looks like I want it to be dark-grey to match the background of the icon. Do we really want to get into clipping paths here? Because the circle is it's own svg element, we probably want the path to be a clipping path instead of coloring it the same color as the background. It seems like overkill on first pass though.

2020-01-12 23:41 UTC, bthaile approved these changes
lgtm

2020-01-12 23:53 UTC, ghost reviewed
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 🌟
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/4kghkx9**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

2020-01-13 16:03 UTC, JohnDanz approved these changes

2020-01-13 16:04 UTC, merged