market creation date time fixes
AugurProject/augur pull request #5503
Opened 2020-01-12 20:59 UTC by bthaile

fixed trading form bug for pre-liquidity
fix date selector for max market end time, had to get off contract.

2020-01-12 21:14 UTC, ghost reviewed
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). ✌️
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/7g6hl99**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

2020-01-13 18:59 UTC, phoebemirman requested changes
see comment

2020-01-13 18:59 UTC, phoebemirman commented on packages/augur-ui/src/modules/create-market/components/review.tsx
> +    this.props.setEnableCreate(noEth || noRep || noDai);
shouldn't we check if they have enough to create the market?

seeing this
<img width="795" alt="Screen Shot 2020-01-13 at 9 13 02 AM" src="https://user-images.githubusercontent.com/6775839/72276522-f2c47b80-35e4-11ea-8bad-bdfae2a45d2c.png">

2020-01-13 19:01 UTC, bthaile commented on packages/augur-ui/src/modules/create-market/components/review.tsx
> +    this.props.setEnableCreate(noEth || noRep || noDai);
this does check if the user has enough to create the market

augur/packages/augur-ui/src/modules/markets/helpers/insufficient-funds.ts

2020-01-13 19:04 UTC, phoebemirman approved these changes

2020-01-13 19:04 UTC, merged