fix spread template
AugurProject/augur pull request #5972
Opened 2020-02-06 14:12 UTC by bthaile

index were off for this template. fixed them now template works. 

![image](https://user-images.githubusercontent.com/3970376/73944575-73ab2600-48b8-11ea-9e11-5213012b4492.png)

2020-02-06 18:34 UTC, phoebemirman approved these changes

2020-02-06 19:21 UTC, pgebheim requested changes
There's merge conflict markets in `templates.ts`

2020-02-07 14:49 UTC, ghost reviewed
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 💪
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/w9jhxre**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

2020-02-07 15:05 UTC, pgebheim approved these changes

2020-02-07 16:33 UTC, merged