Betting UI - loading ellipse icon
AugurProject/augur pull request #6315
Opened 2020-02-20 06:46 UTC by rubyweb3

2020-02-20 07:03 UTC, rubyweb3 commented on packages/augur-ui/src/modules/common/icons.tsx
> +        <linearGradient
There are several ways to achieve linearGradient in LoadingEllipse in trading and betting UIs. Other options:
1. We don't need to support linearGradient in LoadingEllipse
2. We can use a different icon in Betting UI.

@JohnDanz What do you think about it?

2020-02-28 16:01 UTC, JohnDanz requested changes
I'd prefer to use CSS to style this icon, not checking theme on the icon. Ideally theme checking in JS is done extremely rarely and mainly just for logical changes to view routing or if there are different calculations to be made, it shouldn't be used for styling changes.

2020-02-28 16:01 UTC, JohnDanz commented on packages/augur-ui/src/modules/common/icons.tsx
> +        <linearGradient
I think we should be using CSS to handle this instead of directly defining it in the SVG like we do for other SVGs.

so for this we could do something like

```
. CategoryRow {
> span:nth-of-type(2) {
 > svg LinearGradient > stop {
 stopColor: var(--color-primary-text);
}
```
something along those lines

2020-03-01 07:46 UTC, rubyweb3 commented on packages/augur-ui/src/modules/common/icons.tsx
> +        <linearGradient
Updated. It really works. Thank you.

2020-03-03 17:24 UTC, JohnDanz approved these changes

2020-03-03 17:25 UTC, merged