Fix layout and search bar Sportsbook accounts touchups
AugurProject/augur pull request #7753
Opened 2020-05-13 11:21 UTC by rubyweb3

https://github.com/AugurProject/augur/issues/7739

![Screen Shot 2020-05-13 at 7 17 48 PM](https://user-images.githubusercontent.com/58647954/81806313-de6e9c00-954e-11ea-8280-0fdaeb81c790.png)

- The "Your Funds" section is too tall, it looks to be about ~40 px to tall.
- use grid gap instead of margins on the various pieces to create the space between them.
- The Overview chart shouldn't be leaving this whitespace at the bottom, we want the grey background/chart to go all the way to the bottom of this section. (This section is most likely too tall)
- We are missing a count for My Active Markets section and we need to give more space between that count and the search bar on that section as well as any other section with a search bar (see mocks):
![Screen Shot 2020-05-13 at 6 15 43 PM](https://user-images.githubusercontent.com/58647954/81806259-c8f97200-954e-11ea-8118-9864fba34c2d.png)
- The Augur Status section also appears to be too tall, much like overview, we shouldn't have so much dead whitespace below the bottom stats.

2020-05-13 16:21 UTC, JohnDanz commented
<img width="613" alt="Screen Shot 2020-05-13 at 11 18 05 AM" src="https://user-images.githubusercontent.com/10524630/81838248-7d71a480-950b-11ea-8bf7-501c83db1aaf.png">

we need to have this module grow a bit more and not have a scrollbar.

Title also looks a bit too spaced out compared to the mocks.

2020-05-13 16:22 UTC, JohnDanz requested changes
couple notes at the bottom, also still missing some things from the original issue but I assume that is on purpose for now

Edit:

the updated null states look good, need to add the counters to the right of the titles for the market panes however

2020-05-18 10:08 UTC, rubyweb3 commented
> couple notes at the bottom, also still missing some things from the original issue but I assume that is on purpose for now
> 
> Edit:
> 
> the updated null states look good, need to add the counters to the right of the titles for the market panes however

Updated. Thanks

2020-05-18 16:47 UTC, JohnDanz approved these changes

2020-05-18 16:47 UTC, merged