updaate sanitize URL
AugurProject/augur pull request #8251
Opened 2020-06-30 18:18 UTC by andrewdamelio

<img width="333" src="https://user-images.githubusercontent.com/1683736/86161734-b1188600-badb-11ea-86a9-0d4154c38dd5.png">

<img width="333" alt="Screen Shot 2020-06-30 at 2 16 48 PM" src="https://user-images.githubusercontent.com/1683736/86162188-6a775b80-badc-11ea-8572-d8d82a37bff3.png">

<img width="333" src="https://user-images.githubusercontent.com/1683736/86161739-b37ae000-badb-11ea-8eed-527426896f8f.png">

@pgebheim let me know if you think i should add any other TLD's

2020-07-01 04:01 UTC, pgebheim commented
@andrewdamelio After some fiddling I came up with this. It's possible of false positives because urls are weird but I think will work more abstractly without pulling in `tldts` or something.
```
title.replace(/(([a-zA-Z\-_]+)\.)+?\/?/g, "$2(dot)")
```

Examples:
![image](https://user-images.githubusercontent.com/86010/86201611-de355a80-bb14-11ea-9ca2-68f7d2e6be9d.png)
```
[
"This is some test text via www.tradingview.com",
"This could be a title with cdc.gov in it. ",
"Here is a good market. With the resolution via predictions.markets",
"https://www.tradingview.com/aasd",
"cdc.gov/blah",
"https://google.com/asdasd",
"And this one includes a http://weird_url.com/index.html And I wonder if it will work"
].map((u) => {
  return u.replace(/(([a-zA-Z\-_]+)\.)+?\/?/g, "$2(dot)")
});
```

2020-07-01 04:21 UTC, pgebheim requested changes
See feedback :point_up:

2020-07-01 21:07 UTC, pgebheim approved these changes

2020-07-01 21:20 UTC, merged

2020-07-02 12:08 UTC, andrewdamelio commented
@pgebheim Thanks Paul for updating this yesterday