Tomhaile/ch16690/helpers to start pop geth should use file
AugurProject/augur pull request #90
Opened 2018-11-20 23:25 UTC by bthaile

Add ability to create pop docker images. For now have to run `yarn docker:build` in augur-tools dir. Not sure why it stalls when run from root.

Added helper to run augur-core docker image (needed for creating pop dockers) `yarn docker:augur-core`.
Added helper to run augur docker image (needed for creating pop dockers) `yarn docker:augur`

2018-11-24 06:08 UTC, justinbarry requested changes
Left some questions for other team members. Wondering if we can leverage lerna to handle to build all vs using a separate script to do it.

Looks like everything thing is there. Way to do the heavy lifting!

2018-11-24 06:08 UTC, justinbarry commented on packages/augur-node/package.json
> +    "augur.js": "6.0.1",
I changed the version of augur.js to "6.0.0-0" presumably to fix the same issue you had. We should probably move it to "6.0.1" but I leave that to our release master @petong.

2018-11-24 06:08 UTC, justinbarry commented on packages/augur-core/package.json
> -    "@velma/ganache-core": "2.1.0-beta.0-velma-1.0.0-rc.2",
Is it outside the scope of this ticket to upgrade this?

2018-11-24 06:08 UTC, justinbarry commented on packages/augur-core/package.json
> +    "npx": "^10.2.0",
I believe this comes with the system npm install.

2018-11-24 06:08 UTC, justinbarry commented on packages/augur-tools/package.json
> +    "test": "echo \"Error: no test specified\" && exit 1",
@nuevoalex Will this break windows support?

2018-11-24 06:08 UTC, justinbarry commented on packages/augur-tools/scripts/test-pause-unpause-rep.js
> +          augur.api.LegacyReputationToken.transfer(
Some of the contract calls are now promisified. Can this be cleaned up with async/await?

2018-11-24 17:09 UTC, bthaile commented on packages/augur-core/package.json
> -    "@velma/ganache-core": "2.1.0-beta.0-velma-1.0.0-rc.2",
Couldnt get lerna to work. It just hangs. Reason for the script

2018-11-24 17:10 UTC, bthaile commented on packages/augur-tools/scripts/test-pause-unpause-rep.js
> +          augur.api.LegacyReputationToken.transfer(
Was this merged in? I didnt write this

2018-11-24 17:15 UTC, bthaile commented on packages/augur-node/package.json
> +    "augur.js": "6.0.1",
Augur.js version recently got changed. We’ll need to merge thise changes in

2018-11-26 07:54 UTC, justinbarry commented on packages/augur-tools/scripts/test-pause-unpause-rep.js
> +          augur.api.LegacyReputationToken.transfer(
You are right. Showed as a delete/create vs a move. My bad.

2018-11-26 07:56 UTC, justinbarry commented on packages/augur-node/package.json
> +    "augur.js": "6.0.1",
I'm all for that. Everything *should* release in lockstep after we rename everything. In a perfect world, the version changes would happen as a separate PR. Obviously not possible here given it broke the dev workflow.

I'll move this to a separate PR.

2018-11-26 07:59 UTC, justinbarry commented on packages/augur-core/package.json
> -    "@velma/ganache-core": "2.1.0-beta.0-velma-1.0.0-rc.2",
@bthaile Whats up with the version change?

2018-11-26 18:47 UTC, bthaile commented on packages/augur-core/package.json
> +    "npx": "^10.2.0",
remove this lib

2018-11-26 18:48 UTC, bthaile commented on packages/augur-node/package.json
> +    "augur.js": "6.0.1",
merged from master, so it's should be good.

2018-11-26 18:48 UTC, bthaile commented on packages/augur-core/package.json
> -    "@velma/ganache-core": "2.1.0-beta.0-velma-1.0.0-rc.2",
this was added back in, g2g.

2018-11-26 19:20 UTC, justinbarry approved these changes

2018-11-26 19:21 UTC, justinbarry commented
LGTM

2018-11-26 20:42 UTC, merged