Fixed style and mobile animation for bestlip
AugurProject/augur pull request #9517
Opened 2020-10-21 04:24 UTC by bconfortin

#9391

2020-10-21 18:40 UTC, phoebemirman requested changes
not seeing it animate at and around 870px wide

2020-10-21 18:40 UTC, phoebemirman commented on packages/augur-ui/src/modules/trading/betslip.styles.less
> +        bottom: 0.5rem;
can you use constants

2020-10-21 18:40 UTC, phoebemirman commented on packages/augur-ui/src/modules/trading/betslip.styles.less
> +    transition: top .3s cubic-bezier(0.44, 0, 0.56, 1);
we need it to be all for tablet/ this breaks tablet animation

2020-10-22 15:59 UTC, bconfortin commented on packages/augur-ui/src/modules/trading/betslip.styles.less
> +        bottom: 0.5rem;
Oops

2020-10-23 17:09 UTC, phoebemirman requested changes
tablet is missing the semi-transparent background behind the betslip when it is open

2020-10-26 16:15 UTC, phoebemirman approved these changes

2020-10-26 16:15 UTC, merged